#include "ui/strings.hpp"

// All strings are ASCII 32–126 only — the bitmap font does not render accents.
// Accented characters are romanised (e.g. "PARAMETRES" for "PARAMÈTRES").

namespace fridge_ink::ui {

// ── English ───────────────────────────────────────────────────────────────────
static constexpr UiStrings kStringsEn = {
  // Common
  .on  = "ON",
  .off = "OFF",

  // Menu
  .menu_title    = "MENU",
  .menu_memo     = "MEMO",
  .menu_list     = "LIST",
  .menu_timer    = "TIMER",
  .menu_calendar = "CALENDAR",
  .menu_settings = "SETTINGS",
  .menu_hint     = "Rotate to browse. Click to open the selected screen.",

  // Settings
  .settings_title             = "SETTINGS",
  .settings_hint_landscape    = "ROTATE TO SELECT  -  CLICK TO ENTER  -  HOLD TO HOME",
  .settings_hint_portrait     = "ROTATE SELECT  -  CLICK ENTER",
  .settings_group_display     = "DISPLAY",
  .settings_group_sync        = "SYNC",
  .settings_group_other       = "OTHER",
  .settings_font_size         = "FONT SIZE",
  .settings_partial_refresh   = "PARTIAL REFRESH",
  .settings_full_refresh      = "FULL REFRESH",
  .settings_rotation          = "ROTATION",
  .settings_language          = "LANGUAGE",
  .settings_connectivity      = "WIFI + BT",
  .settings_auto_sync         = "AUTO SYNC",
  .settings_sync_now          = "SYNC NOW",
  .settings_change_wifi       = "CHANGE WI-FI",
  .settings_reset             = "RESET / WEB DATA",
  .settings_press_enter       = "PRESS ENTER",
  .settings_retry             = "RETRY",
  .settings_click_again       = "CLICK AGAIN!",
  .settings_not_set           = "NOT SET",
  .settings_syncing           = "SYNCING...",
  .settings_every             = "EVERY",
  .settings_partials          = "PARTIALS",
  .settings_last_sync_prefix  = "LAST SYNC",
  .settings_last_sync_failed  = "LAST SYNC FAILED",
  .settings_last_sync_never   = "LAST SYNC: NEVER",
  .settings_sync_ok           = "LAST SYNC OK",
  .settings_sync_in_progress  = "SYNC IN PROGRESS",
  .settings_sync_fail         = "LAST SYNC FAIL",
  .settings_sync_never        = "LAST SYNC NEVER",
  .settings_small             = "SMALL",
  .settings_medium            = "MEDIUM",
  .settings_large             = "LARGE",
  .settings_slow              = "SLOW",
  .settings_balanced          = "BALANCED",
  .settings_fast              = "FAST",
  .settings_never             = "NEVER",
  .settings_invalid_time      = "INVALID TIME",

  // Timer
  .timer_title      = "TIMER",
  .timer_hint       = "ROTATE=SELECT  |  CLICK=ENTER  |  HOLD=HOME",
  .timer_ready      = "READY",
  .timer_running    = "RUNNING",
  .timer_paused     = "PAUSED",
  .timer_pause_btn  = "PAUSE",
  .timer_start_btn  = "START",
  .timer_reset_btn  = "RESET",
  .timer_1min_done  = "1 MINUTE COUNTDOWN FINISHED",
  .timer_mins_done  = " MINUTES COUNTDOWN FINISHED",

  // Memo
  .memo_title        = "FAMILY BOARD",
  .memo_hint         = "ROTATE=SELECT  |  CLICK=ENTER  |  HOLD=HOME",
  .memo_empty        = "NO FAMILY NOTES YET",
  .memo_empty_voice  = "TRY VOICE: LEAVE A NOTE DINNER IS READY",
  .memo_badge_new    = "NEW",
  .memo_total        = "TOTAL",
  .memo_count_new    = "NEW",
  .memo_focus        = "FOCUS",
  .memo_showing      = "SHOWING",
  .memo_of           = "OF",
  .memo_footer       = "VOICE CMD: ADD | DELETE | CLEAR",
  .memo_unknown      = "UNKNOWN",
  .memo_unknown_time = "UNKNOWN TIME",

  // List
  .list_title     = "LIST",
  .list_hint      = "ROTATE=SELECT  |  CLICK=TOGGLE  |  HOLD=HOME",
  .list_inventory = "INVENTORY",
  .list_reminder  = "REMINDER",
  .list_no_items  = "NO ITEMS",
  .list_done      = "DONE",
  .list_todo      = "TODO",
  .list_footer    = "VOICE CMD: DELETE | ADD | MODIFY",

  // Calendar
  .cal_sun             = "SUN",
  .cal_mon             = "MON",
  .cal_tue             = "TUE",
  .cal_wed             = "WED",
  .cal_thu             = "THU",
  .cal_fri             = "FRI",
  .cal_sat             = "SAT",
  .cal_month_view      = "MONTH VIEW",
  .cal_agenda          = "AGENDA",
  .cal_mode_agenda     = "MODE: AGENDA",
  .cal_mode_date       = "MODE: DATE",
  .cal_no_events       = "NO EVENTS",
  .cal_voice_hint      = "Voice can add reminders and memos",
  .cal_voice_hint_upper = "VOICE CAN ADD REMINDERS AND MEMOS",
  .cal_reminder        = "REMINDER",
  .cal_event           = "EVENT",
  .cal_task            = "TASK",
  .cal_click_toggle    = "CLICK TO TOGGLE",
  .cal_event_readonly  = "EVENT (READ ONLY)",
  .cal_more            = "MORE",
  .cal_day             = "DAY",
  .cal_due_prefix      = "DUE: ",

  // Weather landscape
  .wx_feels_like    = "FEELS LIKE",
  .wx_feels_like_na = "FEELS LIKE --",
  .wx_syncing       = "SYNCING...",
  .wx_humidity      = "HUMIDITY",
  .wx_wind          = "WIND",
  .wx_uv_index      = "UV INDEX",

  // Weather portrait
  .wx_feels_like_lc   = "Feels Like",
  .wx_no_weather_data    = "No weather data",
  .wx_unknown_location   = "Unknown",
  .wx_syncing_lc      = "Syncing...",
  .wx_waiting_sync    = "Waiting for sync",
  .wx_waiting_wifi    = "Waiting for WiFi",
  .wx_humidity_lc     = "Humidity",
  .wx_wind_lc         = "Wind",
  .wx_uv_index_lc     = "UV Index",

  // Onboarding
  .ob_title               = "FIRST SETUP",
  .ob_step_prefix         = "STEP",
  .ob_configure_wifi      = "CONFIGURE WI-FI AND BASIC PREFERENCES.",
  .ob_connect_wifi        = "CONNECT TO WI-FI TO ENABLE WEATHER AND SYNC.",
  .ob_select_wifi         = "SELECT WI-FI",
  .ob_skip_now            = "SKIP FOR NOW",
  .ob_rotate_choose_press = "ROTATE TO CHOOSE  -  PRESS TO CONTINUE",
  .ob_select_network      = "SELECT WI-FI NETWORK",
  .ob_press_rescan        = "PRESS TO RESCAN",
  .ob_rotate_scroll       = "ROTATE TO SCROLL  -  PRESS TO SELECT",
  .ob_skip                = "SKIP",
  .ob_network             = "NETWORK:",
  .ob_quick_prefs         = "QUICK PREFERENCES",
  .ob_change_later        = "YOU CAN CHANGE THESE LATER IN SETTINGS.",
  .ob_language            = "LANGUAGE",
  .ob_timezone            = "TIMEZONE",
  .ob_auto_sync           = "AUTO SYNC",
  .ob_timezone_prefix     = "Timezone: ",
  .ob_auto_sync_prefix    = "Auto Sync: ",
  .ob_wifi_prefix         = "Wi-Fi: ",
  .ob_language_prefix     = "Language: ",
  .ob_next_step           = "NEXT STEP ->",
  .ob_voice_guide         = "VOICE GUIDE >",
  .ob_hold_to_record      = "HOLD VOICE KEY TO RECORD",
  .ob_recording           = "* RECORDING... SPEAK NOW *",
  .ob_example_cmds        = "EXAMPLE COMMANDS:",
  .ob_ex_add_milk         = "* Add milk to the shopping list",
  .ob_ex_set_timer        = "* Set a 5-minute timer",
  .ob_ex_show_cal         = "* Show the calendar",
  .ob_result              = "RESULT:",
  .ob_no_result           = "No result yet.",
  .ob_hold_to_test        = "Hold the voice key above to test.",
  .ob_listening           = "Listening...",
  .ob_press_skip          = "Press to skip voice test and open Home.",
  .ob_done_btn            = "DONE >",
  .ob_skip_btn            = "SKIP >",
  .ob_setup_complete      = "SETUP COMPLETE",
  .ob_board_ready         = "YOUR BOARD IS READY.",
  .ob_enter_home          = "ENTER HOME",

  // Home screen
  .home_inventory     = "INVENTORY",
  .home_reminders     = "REMINDERS",
  .home_stocked       = "STOCKED",
  .home_out           = "OUT",
  .home_navigation    = "NAVIGATION",
  .home_syncing       = "SYNCING",
  .home_unsynced      = "UNSYNCED",
  .home_hum_prefix    = "HUM ",
  .home_hum_na        = "HUM --",
  .home_hold_to_talk  = "Hold to talk",

  // Landing
  .land_subtitle      = "Welcome. Learn controls before first setup.",
  .land_tip_rotate    = "Rotate",
  .land_tip_press     = "Press",
  .land_tip_long      = "Long Press",
  .land_tip_voice     = "Hold Voice Key",
  .land_tip_move_focus = "MOVE FOCUS",
  .land_tip_confirm   = "CONFIRM",
  .land_tip_back_home = "BACK TO HOME",
  .land_tip_talk      = "TALK TO ASSISTANT",
  .land_voice_unlock  = "VOICE KEY UNLOCKS AFTER FIRST SETUP.",
  .land_language      = "Language",
  .land_status_done   = "SETUP COMPLETE. PRESS CLICK TO OPEN HOME.",
  .land_status_choose = "ROTATE TO CHOOSE LANGUAGE, THEN CLICK TO START SETUP.",
  .land_cta_home      = "Enter Home",
  .land_cta_rotate    = "Rotate to choose language",
  .land_cta_click     = "Click to start onboarding",
  // Detail scaffold
  .scaffold_return_menu = "CLICK TO RETURN MENU",
};

// ── Spanish (es-ES) ───────────────────────────────────────────────────────────
// Accents are romanised: e.g. "AJUSTES" not "AJÚSTES", "SINC." not "SINC.".
static constexpr UiStrings kStringsEs = {
  // Common
  .on  = "SI",
  .off = "NO",

  // Menu
  .menu_title    = "MENU",
  .menu_memo     = "NOTAS",
  .menu_list     = "LISTA",
  .menu_timer    = "TEMPORIZADOR",
  .menu_calendar = "CALENDARIO",
  .menu_settings = "AJUSTES",
  .menu_hint     = "Girar para navegar. Pulsar para abrir la pantalla.",

  // Settings
  .settings_title             = "AJUSTES",
  .settings_hint_landscape    = "GIRAR PARA SELEC.  -  PULSAR PARA ENTRAR  -  MANTENER PARA INICIO",
  .settings_hint_portrait     = "GIRAR SELEC.  -  PULSAR ENTRAR",
  .settings_group_display     = "PANTALLA",
  .settings_group_sync        = "SINCRONIZACION",
  .settings_group_other       = "OTRO",
  .settings_font_size         = "TAMANO FUENTE",
  .settings_partial_refresh   = "REFRESCO PARCIAL",
  .settings_full_refresh      = "REFRESCO COMPLETO",
  .settings_rotation          = "ROTACION",
  .settings_language          = "IDIOMA",
  .settings_connectivity      = "WIFI + BT",
  .settings_auto_sync         = "SINC. AUTO.",
  .settings_sync_now          = "SINCRONIZAR",
  .settings_change_wifi       = "CAMBIAR WI-FI",
  .settings_reset             = "RESET / DATOS WEB",
  .settings_press_enter       = "PULSAR ENTER",
  .settings_retry             = "REINTENTAR",
  .settings_click_again       = "PULSAR DE NUEVO!",
  .settings_not_set           = "NO CONFIGURADO",
  .settings_syncing           = "SINCRONIZANDO...",
  .settings_every             = "CADA",
  .settings_partials          = "PARCIALES",
  .settings_last_sync_prefix  = "ULTIMA SINC.",
  .settings_last_sync_failed  = "ULTIMA SINC. FALLIDA",
  .settings_last_sync_never   = "SIN SINCRONIZACION",
  .settings_sync_ok           = "ULTIMA SINC. OK",
  .settings_sync_in_progress  = "SINC. EN CURSO",
  .settings_sync_fail         = "ULTIMA SINC. FALLO",
  .settings_sync_never        = "SIN SINCRONIZACION",
  .settings_small             = "PEQUENO",
  .settings_medium            = "MEDIANO",
  .settings_large             = "GRANDE",
  .settings_slow              = "LENTO",
  .settings_balanced          = "EQUILIBRADO",
  .settings_fast              = "RAPIDO",
  .settings_never             = "NUNCA",
  .settings_invalid_time      = "HORA INVALIDA",

  // Timer
  .timer_title      = "TEMPORIZADOR",
  .timer_hint       = "GIRAR=SELEC.  |  PULSAR=ENTRAR  |  MANTENER=INICIO",
  .timer_ready      = "LISTO",
  .timer_running    = "EN CURSO",
  .timer_paused     = "PAUSADO",
  .timer_pause_btn  = "PAUSA",
  .timer_start_btn  = "INICIAR",
  .timer_reset_btn  = "REINICIAR",
  .timer_1min_done  = "CUENTA ATRAS DE 1 MINUTO FINALIZADA",
  .timer_mins_done  = " MINUTOS CUENTA ATRAS FINALIZADA",

  // Memo
  .memo_title        = "TABLON FAMILIAR",
  .memo_hint         = "GIRAR=SELEC.  |  PULSAR=ENTRAR  |  MANTENER=INICIO",
  .memo_empty        = "SIN NOTAS FAMILIARES",
  .memo_empty_voice  = "USA LA VOZ: DEJA UNA NOTA LA CENA ESTA LISTA",
  .memo_badge_new    = "NUEVO",
  .memo_total        = "TOTAL",
  .memo_count_new    = "NUEVO",
  .memo_focus        = "ENFOQUE",
  .memo_showing      = "MOSTRANDO",
  .memo_of           = "DE",
  .memo_footer       = "CMD VOZ: ANADIR | ELIMINAR | BORRAR",
  .memo_unknown      = "DESCONOCIDO",
  .memo_unknown_time = "HORA DESCONOCIDA",

  // List
  .list_title     = "LISTA",
  .list_hint      = "GIRAR=SELEC.  |  PULSAR=ALTERNAR  |  MANTENER=INICIO",
  .list_inventory = "INVENTARIO",
  .list_reminder  = "RECORDATORIO",
  .list_no_items  = "SIN ARTICULOS",
  .list_done      = "HECHO",
  .list_todo      = "PENDIENTE",
  .list_footer    = "CMD VOZ: ELIMINAR | ANADIR | MODIFICAR",

  // Calendar
  .cal_sun             = "DOM",
  .cal_mon             = "LUN",
  .cal_tue             = "MAR",
  .cal_wed             = "MIE",
  .cal_thu             = "JUE",
  .cal_fri             = "VIE",
  .cal_sat             = "SAB",
  .cal_month_view      = "VISTA MENSUAL",
  .cal_agenda          = "AGENDA",
  .cal_mode_agenda     = "MODO: AGENDA",
  .cal_mode_date       = "MODO: FECHA",
  .cal_no_events       = "SIN EVENTOS",
  .cal_voice_hint      = "La voz puede anadir recordatorios y notas",
  .cal_voice_hint_upper = "LA VOZ PUEDE ANADIR RECORDATORIOS Y NOTAS",
  .cal_reminder        = "RECORDATORIO",
  .cal_event           = "EVENTO",
  .cal_task            = "TAREA",
  .cal_click_toggle    = "PULSAR PARA ALTERNAR",
  .cal_event_readonly  = "EVENTO (SOLO LECTURA)",
  .cal_more            = "MAS",
  .cal_day             = "DIA",
  .cal_due_prefix      = "VENCE: ",

  // Weather landscape
  .wx_feels_like    = "SENSACION TERMICA",
  .wx_feels_like_na = "SENSACION TERMICA --",
  .wx_syncing       = "SINCRONIZANDO...",
  .wx_humidity      = "HUMEDAD",
  .wx_wind          = "VIENTO",
  .wx_uv_index      = "INDICE UV",

  // Weather portrait
  .wx_feels_like_lc   = "Sensacion Termica",
  .wx_no_weather_data    = "Sin datos del tiempo",
  .wx_unknown_location   = "Desconocido",
  .wx_syncing_lc      = "Sincronizando...",
  .wx_waiting_sync    = "Esperando sincronizacion",
  .wx_waiting_wifi    = "Esperando WiFi",
  .wx_humidity_lc     = "Humedad",
  .wx_wind_lc         = "Viento",
  .wx_uv_index_lc     = "Indice UV",

  // Onboarding
  .ob_title               = "PRIMERA CONFIGURACION",
  .ob_step_prefix         = "PASO",
  .ob_configure_wifi      = "CONFIGURA EL WI-FI Y LAS PREFERENCIAS BASICAS.",
  .ob_connect_wifi        = "CONECTA AL WI-FI PARA HABILITAR EL TIEMPO Y LA SINC.",
  .ob_select_wifi         = "SELECCIONAR WI-FI",
  .ob_skip_now            = "OMITIR POR AHORA",
  .ob_rotate_choose_press = "GIRAR PARA ELEGIR  -  PULSAR PARA CONTINUAR",
  .ob_select_network      = "SELECCIONAR RED WI-FI",
  .ob_press_rescan        = "PULSAR PARA BUSCAR",
  .ob_rotate_scroll       = "GIRAR PARA DESPLAZAR  -  PULSAR PARA SELECCIONAR",
  .ob_skip                = "OMITIR",
  .ob_network             = "RED:",
  .ob_quick_prefs         = "PREFERENCIAS RAPIDAS",
  .ob_change_later        = "PUEDES CAMBIARLO MAS TARDE EN AJUSTES.",
  .ob_language            = "IDIOMA",
  .ob_timezone            = "ZONA HORARIA",
  .ob_auto_sync           = "SINC. AUTO.",
  .ob_timezone_prefix     = "Zona horaria: ",
  .ob_auto_sync_prefix    = "Sinc. auto.: ",
  .ob_wifi_prefix         = "Wi-Fi: ",
  .ob_language_prefix     = "Idioma: ",
  .ob_next_step           = "SIGUIENTE ->",
  .ob_voice_guide         = "GUIA DE VOZ >",
  .ob_hold_to_record      = "MANTENER TECLA VOZ PARA GRABAR",
  .ob_recording           = "* GRABANDO... HABLA AHORA *",
  .ob_example_cmds        = "COMANDOS DE EJEMPLO:",
  .ob_ex_add_milk         = "* Anadir leche a la lista de la compra",
  .ob_ex_set_timer        = "* Poner un temporizador de 5 minutos",
  .ob_ex_show_cal         = "* Mostrar el calendario",
  .ob_result              = "RESULTADO:",
  .ob_no_result           = "Sin resultado todavia.",
  .ob_hold_to_test        = "Manten la tecla de voz para probar.",
  .ob_listening           = "Escuchando...",
  .ob_press_skip          = "Pulsar para omitir la prueba de voz y abrir el inicio.",
  .ob_done_btn            = "LISTO >",
  .ob_skip_btn            = "OMITIR >",
  .ob_setup_complete      = "CONFIGURACION COMPLETA",
  .ob_board_ready         = "TU TABLERO ESTA LISTO.",
  .ob_enter_home          = "IR AL INICIO",

  // Home screen
  .home_inventory     = "INVENTARIO",
  .home_reminders     = "RECORDATORIOS",
  .home_stocked       = "STOCK",
  .home_out           = "AGOTADO",
  .home_navigation    = "NAVEGACION",
  .home_syncing       = "SINCRONIZANDO",
  .home_unsynced      = "SIN SINC.",
  .home_hum_prefix    = "HUM ",
  .home_hum_na        = "HUM --",
  .home_hold_to_talk  = "Mantener para hablar",

  // Landing
  .land_subtitle      = "Bienvenido. Aprende los controles antes de configurar.",
  .land_tip_rotate    = "Girar",
  .land_tip_press     = "Pulsar",
  .land_tip_long      = "Pulsar Largo",
  .land_tip_voice     = "Mantener Tecla Voz",
  .land_tip_move_focus = "MOVER FOCO",
  .land_tip_confirm   = "CONFIRMAR",
  .land_tip_back_home = "VOLVER AL INICIO",
  .land_tip_talk      = "HABLAR CON IA",
  .land_voice_unlock  = "LA TECLA VOZ SE ACTIVA TRAS LA CONFIGURACION.",
  .land_language      = "Idioma",
  .land_status_done   = "CONFIGURACION COMPLETA. PULSAR CLICK PARA ABRIR INICIO.",
  .land_status_choose = "GIRAR PARA ELEGIR IDIOMA, PULSAR PARA INICIAR CONFIGURACION.",
  .land_cta_home      = "Ir al Inicio",
  .land_cta_rotate    = "Girar para elegir idioma",
  .land_cta_click     = "Pulsar para iniciar configuracion",
  // Detail scaffold
  .scaffold_return_menu = "PULSAR PARA VOLVER AL MENU",
};

// ── French (fr-FR) ────────────────────────────────────────────────────────────
// Accents are romanised: "PARAMETRES" not "PARAMÈTRES", etc.
static constexpr UiStrings kStringsFr = {
  // Common
  .on  = "OUI",
  .off = "NON",

  // Menu
  .menu_title    = "MENU",
  .menu_memo     = "NOTE",
  .menu_list     = "LISTE",
  .menu_timer    = "MINUTEUR",
  .menu_calendar = "CALENDRIER",
  .menu_settings = "PARAMETRES",
  .menu_hint     = "Tourner pour naviguer. Appuyer pour ouvrir l'ecran.",

  // Settings
  .settings_title             = "PARAMETRES",
  .settings_hint_landscape    = "TOURNER POUR SEL.  -  APPUYER POUR ENTRER  -  MAINTENIR ACCUEIL",
  .settings_hint_portrait     = "TOURNER SEL.  -  APPUYER ENTRER",
  .settings_group_display     = "AFFICHAGE",
  .settings_group_sync        = "SYNCHRONISATION",
  .settings_group_other       = "AUTRE",
  .settings_font_size         = "TAILLE POLICE",
  .settings_partial_refresh   = "RAFRAICH. PARTIEL",
  .settings_full_refresh      = "RAFRAICH. COMPLET",
  .settings_rotation          = "ROTATION",
  .settings_language          = "LANGUE",
  .settings_connectivity      = "WIFI + BT",
  .settings_auto_sync         = "SYNCHRO AUTO",
  .settings_sync_now          = "SYNCHRONISER",
  .settings_change_wifi       = "CHANGER WI-FI",
  .settings_reset             = "RESET / DONNEES WEB",
  .settings_press_enter       = "APPUYER ENTREE",
  .settings_retry             = "REESSAYER",
  .settings_click_again       = "APPUYER A NOUVEAU!",
  .settings_not_set           = "NON CONFIGURE",
  .settings_syncing           = "SYNCHRONISATION...",
  .settings_every             = "TOUS LES",
  .settings_partials          = "PARTIELS",
  .settings_last_sync_prefix  = "DERN. SYNCHRO",
  .settings_last_sync_failed  = "DERN. SYNCHRO ECHOUEE",
  .settings_last_sync_never   = "JAMAIS SYNCHRONISE",
  .settings_sync_ok           = "DERN. SYNCHRO OK",
  .settings_sync_in_progress  = "SYNCHRO EN COURS",
  .settings_sync_fail         = "DERN. SYNCHRO ECHEC",
  .settings_sync_never        = "JAMAIS SYNCHRONISE",
  .settings_small             = "PETITE",
  .settings_medium            = "MOYENNE",
  .settings_large             = "GRANDE",
  .settings_slow              = "LENTE",
  .settings_balanced          = "EQUILIBRE",
  .settings_fast              = "RAPIDE",
  .settings_never             = "JAMAIS",
  .settings_invalid_time      = "HEURE INVALIDE",

  // Timer
  .timer_title      = "MINUTEUR",
  .timer_hint       = "TOURNER=SEL.  |  APPUYER=ENTRER  |  MAINTENIR=ACCUEIL",
  .timer_ready      = "PRET",
  .timer_running    = "EN COURS",
  .timer_paused     = "EN PAUSE",
  .timer_pause_btn  = "PAUSE",
  .timer_start_btn  = "DEMARRER",
  .timer_reset_btn  = "REINIT.",
  .timer_1min_done  = "COMPTE A REBOURS DE 1 MINUTE TERMINE",
  .timer_mins_done  = " MINUTES COMPTE A REBOURS TERMINE",

  // Memo
  .memo_title        = "TABLEAU FAMILIAL",
  .memo_hint         = "TOURNER=SEL.  |  APPUYER=ENTRER  |  MAINTENIR=ACCUEIL",
  .memo_empty        = "AUCUNE NOTE FAMILIALE",
  .memo_empty_voice  = "ESSAYEZ: LAISSER UNE NOTE LE DINER EST PRET",
  .memo_badge_new    = "NOUVEAU",
  .memo_total        = "TOTAL",
  .memo_count_new    = "NOUVEAU",
  .memo_focus        = "FOCUS",
  .memo_showing      = "AFFICHAGE",
  .memo_of           = "SUR",
  .memo_footer       = "CMD VOIX: AJOUTER | SUPPRIMER | EFFACER",
  .memo_unknown      = "INCONNU",
  .memo_unknown_time = "HEURE INCONNUE",

  // List
  .list_title     = "LISTE",
  .list_hint      = "TOURNER=SEL.  |  APPUYER=BASCULER  |  MAINTENIR=ACCUEIL",
  .list_inventory = "INVENTAIRE",
  .list_reminder  = "RAPPEL",
  .list_no_items  = "AUCUN ARTICLE",
  .list_done      = "TERMINE",
  .list_todo      = "A FAIRE",
  .list_footer    = "CMD VOIX: SUPPRIMER | AJOUTER | MODIFIER",

  // Calendar
  .cal_sun             = "DIM",
  .cal_mon             = "LUN",
  .cal_tue             = "MAR",
  .cal_wed             = "MER",
  .cal_thu             = "JEU",
  .cal_fri             = "VEN",
  .cal_sat             = "SAM",
  .cal_month_view      = "VUE MENSUELLE",
  .cal_agenda          = "AGENDA",
  .cal_mode_agenda     = "MODE: AGENDA",
  .cal_mode_date       = "MODE: DATE",
  .cal_no_events       = "AUCUN EVENEMENT",
  .cal_voice_hint      = "La voix peut ajouter rappels et notes",
  .cal_voice_hint_upper = "LA VOIX PEUT AJOUTER RAPPELS ET NOTES",
  .cal_reminder        = "RAPPEL",
  .cal_event           = "EVENEMENT",
  .cal_task            = "TACHE",
  .cal_click_toggle    = "CLIC POUR BASCULER",
  .cal_event_readonly  = "EVENEMENT (LECTURE SEULE)",
  .cal_more            = "DE PLUS",
  .cal_day             = "JOUR",
  .cal_due_prefix      = "ECH.: ",

  // Weather landscape
  .wx_feels_like    = "RESSENTI",
  .wx_feels_like_na = "RESSENTI --",
  .wx_syncing       = "SYNCHRONISATION...",
  .wx_humidity      = "HUMIDITE",
  .wx_wind          = "VENT",
  .wx_uv_index      = "INDICE UV",

  // Weather portrait
  .wx_feels_like_lc   = "Ressenti",
  .wx_no_weather_data    = "Pas de donnees meteo",
  .wx_unknown_location   = "Inconnu",
  .wx_syncing_lc      = "Synchronisation...",
  .wx_waiting_sync    = "En attente de synchro",
  .wx_waiting_wifi    = "En attente de WiFi",
  .wx_humidity_lc     = "Humidite",
  .wx_wind_lc         = "Vent",
  .wx_uv_index_lc     = "Indice UV",

  // Onboarding
  .ob_title               = "PREMIERE CONFIGURATION",
  .ob_step_prefix         = "ETAPE",
  .ob_configure_wifi      = "CONFIGUREZ LE WI-FI ET LES PREFERENCES DE BASE.",
  .ob_connect_wifi        = "CONNECTEZ AU WI-FI POUR ACTIVER LA METEO ET LA SYNCHRO.",
  .ob_select_wifi         = "SELECTIONNER WI-FI",
  .ob_skip_now            = "IGNORER POUR L'INSTANT",
  .ob_rotate_choose_press = "TOURNER POUR CHOISIR  -  APPUYER POUR CONTINUER",
  .ob_select_network      = "SELECTIONNER RESEAU WI-FI",
  .ob_press_rescan        = "APPUYER POUR RECHERCHER",
  .ob_rotate_scroll       = "TOURNER POUR DEFILER  -  APPUYER POUR SELECTIONNER",
  .ob_skip                = "IGNORER",
  .ob_network             = "RESEAU:",
  .ob_quick_prefs         = "PREFERENCES RAPIDES",
  .ob_change_later        = "VOUS POUVEZ MODIFIER CES REGLAGES DANS PARAMETRES.",
  .ob_language            = "LANGUE",
  .ob_timezone            = "FUSEAU HORAIRE",
  .ob_auto_sync           = "SYNCHRO AUTO",
  .ob_timezone_prefix     = "Fuseau horaire: ",
  .ob_auto_sync_prefix    = "Synchro auto: ",
  .ob_wifi_prefix         = "Wi-Fi: ",
  .ob_language_prefix     = "Langue: ",
  .ob_next_step           = "SUIVANT ->",
  .ob_voice_guide         = "GUIDE VOIX >",
  .ob_hold_to_record      = "MAINTENIR TOUCHE VOIX POUR ENREGISTRER",
  .ob_recording           = "* ENREGISTREMENT... PARLEZ MAINTENANT *",
  .ob_example_cmds        = "EXEMPLES DE COMMANDES:",
  .ob_ex_add_milk         = "* Ajouter du lait a la liste de courses",
  .ob_ex_set_timer        = "* Mettre un minuteur de 5 minutes",
  .ob_ex_show_cal         = "* Afficher le calendrier",
  .ob_result              = "RESULTAT:",
  .ob_no_result           = "Aucun resultat pour l'instant.",
  .ob_hold_to_test        = "Maintenez la touche voix pour tester.",
  .ob_listening           = "Ecoute...",
  .ob_press_skip          = "Appuyer pour ignorer le test vocal et ouvrir l'accueil.",
  .ob_done_btn            = "TERMINE >",
  .ob_skip_btn            = "IGNORER >",
  .ob_setup_complete      = "CONFIGURATION TERMINEE",
  .ob_board_ready         = "VOTRE TABLEAU EST PRET.",
  .ob_enter_home          = "ALLER A L'ACCUEIL",

  // Home screen
  .home_inventory     = "INVENTAIRE",
  .home_reminders     = "RAPPELS",
  .home_stocked       = "STOCK",
  .home_out           = "EPUISE",
  .home_navigation    = "NAVIGATION",
  .home_syncing       = "SYNCHRO.",
  .home_unsynced      = "NON SYNCHRO.",
  .home_hum_prefix    = "HUM ",
  .home_hum_na        = "HUM --",
  .home_hold_to_talk  = "Maintenir pour parler",

  // Landing
  .land_subtitle      = "Bienvenue. Apprenez les commandes avant la configuration.",
  .land_tip_rotate    = "Tourner",
  .land_tip_press     = "Appuyer",
  .land_tip_long      = "Appui Long",
  .land_tip_voice     = "Maintenir Touche Voix",
  .land_tip_move_focus = "DEPLACER FOCUS",
  .land_tip_confirm   = "CONFIRMER",
  .land_tip_back_home = "RETOUR ACCUEIL",
  .land_tip_talk      = "PARLER A L'IA",
  .land_voice_unlock  = "LA TOUCHE VOIX S'ACTIVE APRES CONFIGURATION.",
  .land_language      = "Langue",
  .land_status_done   = "CONFIGURATION TERMINEE. APPUYER POUR OUVRIR L'ACCUEIL.",
  .land_status_choose = "TOURNER POUR CHOISIR LA LANGUE, PUIS APPUYER POUR CONFIGURER.",
  .land_cta_home      = "Aller a l'accueil",
  .land_cta_rotate    = "Tourner pour choisir la langue",
  .land_cta_click     = "Appuyer pour configurer",
  // Detail scaffold
  .scaffold_return_menu = "CLIQUER POUR RETOURNER AU MENU",
};

// ── Selector ──────────────────────────────────────────────────────────────────
const UiStrings& get_ui_strings(app::Language lang) {
  switch (lang) {
    case app::Language::EsEs: return kStringsEs;
    case app::Language::FrFr: return kStringsFr;
    case app::Language::EnUs:
    default:                  return kStringsEn;
  }
}

}  // namespace fridge_ink::ui
