#!/usr/bin/env python3

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "firmware" / "main" / "ui" / "panel_font_assets_generated.hpp"
FONT_DIR = REPO_ROOT / "assets" / "fonts"

CHARSET = "".join(chr(code) for code in range(32, 127))


@dataclass(frozen=True)
class FontSpec:
    var_name: str
    font_key: str
    filename: str
    size: int


FONT_SPECS = (
    FontSpec("kFontInterBlack84", "inter_black_84", "Inter-Black.ttf", 84),
    FontSpec("kFontInterBlack87", "inter_black_87", "Inter-Black.ttf", 87),
    FontSpec("kFontInterBlack109", "inter_black_109", "Inter-Black.ttf", 109),
    FontSpec("kFontInterBlack66", "inter_black_66", "Inter-Black.ttf", 66),
    FontSpec("kFontInterBlack36", "inter_black_36", "Inter-Black.ttf", 36),
    FontSpec("kFontInterBlack29", "inter_black_29", "Inter-Black.ttf", 29),
    FontSpec("kFontInterBold29", "inter_bold_29", "Inter-Bold.ttf", 29),
    FontSpec("kFontInterBold22", "inter_bold_22", "Inter-Bold.ttf", 22),
    FontSpec("kFontInterBold20", "inter_bold_20", "Inter-Bold.ttf", 20),
    FontSpec("kFontInterMedium18", "inter_medium_18", "Inter-Medium.ttf", 18),
    FontSpec("kFontInterMedium13", "inter_medium_13", "Inter-Medium.ttf", 13),
    FontSpec("kFontInterBold18", "inter_bold_18", "Inter-Bold.ttf", 18),
    FontSpec("kFontInterBold17", "inter_bold_17", "Inter-Bold.ttf", 17),
    FontSpec("kFontInterBold13", "inter_bold_13", "Inter-Bold.ttf", 13),
    FontSpec("kFontInterSemiBold15", "inter_semibold_15", "Inter-SemiBold.ttf", 15),
    FontSpec("kFontInterSemiBold13", "inter_semibold_13", "Inter-SemiBold.ttf", 13),
    FontSpec("kFontJetExtraBold109", "jet_extrabold_109", "JetBrainsMono-ExtraBold.ttf", 109),
    FontSpec("kFontJetExtraBold124", "jet_extrabold_124", "JetBrainsMono-ExtraBold.ttf", 124),
    FontSpec("kFontJetExtraBold66", "jet_extrabold_66", "JetBrainsMono-ExtraBold.ttf", 66),
    FontSpec("kFontJetExtraBold16", "jet_extrabold_16", "JetBrainsMono-ExtraBold.ttf", 16),
    FontSpec("kFontJetBold15", "jet_bold_15", "JetBrainsMono-Bold.ttf", 15),
    FontSpec("kFontJetBold13", "jet_bold_13", "JetBrainsMono-Bold.ttf", 13),
    FontSpec("kFontPlayfairBold28", "playfair_bold_28", "PlayfairDisplay-Bold.ttf", 28),
)


def _pack_bitmap(image: Image.Image) -> list[int]:
    width, height = image.size
    row_bytes = (width + 7) // 8
    out = [0] * (row_bytes * height)
    for y in range(height):
        for x in range(width):
            if image.getpixel((x, y)):
                out[y * row_bytes + (x // 8)] |= 0x80 >> (x % 8)
    return out


def _load_font(path: Path, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(path), size)


def _render_glyph(font: ImageFont.FreeTypeFont, ch: str) -> tuple[dict, list[int]]:
    ascent, descent = font.getmetrics()
    bbox = font.getbbox(ch)
    if bbox is None:
        bbox = (0, 0, 0, 0)
    left, top, right, bottom = (int(v) for v in bbox)
    width = max(0, right - left)
    height = max(0, bottom - top)
    advance = max(1, int(math.ceil(font.getlength(ch))))

    if width == 0 or height == 0:
      return (
          {
              "width": 0,
              "height": 0,
              "left": left,
              "top": top,
              "advance": advance,
              "ascent": ascent,
              "descent": descent,
          },
          [],
      )

    image = Image.new("1", (width, height), 0)
    draw = ImageDraw.Draw(image)
    try:
        draw.fontmode = "1"
    except Exception:
        pass
    draw.text((-left, -top), ch, font=font, fill=1)
    return (
        {
            "width": width,
            "height": height,
            "left": left,
            "top": top,
            "advance": advance,
            "ascent": ascent,
            "descent": descent,
        },
        _pack_bitmap(image),
    )


def _format_bytes(values: list[int], indent: str = "    ") -> str:
    lines: list[str] = []
    chunk: list[str] = []
    for idx, value in enumerate(values):
        chunk.append(f"0x{value:02X}")
        if len(chunk) == 16 or idx == len(values) - 1:
            lines.append(indent + ", ".join(chunk))
            chunk = []
    return ",\n".join(lines)


def generate() -> str:
    out: list[str] = []
    out.append("// Generated by tools/generate_firmware_font_assets.py")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstddef>")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace fridge_ink::platform::panel_font_assets {")
    out.append("")
    out.append("struct Glyph {")
    out.append("  std::uint32_t bitmap_offset;")
    out.append("  std::uint8_t width;")
    out.append("  std::uint8_t height;")
    out.append("  std::int8_t left;")
    out.append("  std::int8_t top;")
    out.append("  std::uint8_t advance;")
    out.append("};")
    out.append("")
    out.append("struct BitmapFont {")
    out.append("  const char* key;")
    out.append("  std::uint8_t size;")
    out.append("  std::uint8_t ascent;")
    out.append("  std::uint8_t descent;")
    out.append("  std::uint8_t line_height;")
    out.append("  const Glyph* glyphs;")
    out.append("  const std::uint8_t* bitmap;")
    out.append("  std::size_t bitmap_size;")
    out.append("};")
    out.append("")

    for spec in FONT_SPECS:
        font = _load_font(FONT_DIR / spec.filename, spec.size)
        ascent, descent = font.getmetrics()
        line_height = ascent + descent
        glyph_rows: list[str] = []
        bitmap: list[int] = []
        offset = 0
        for ch in CHARSET:
            meta, packed = _render_glyph(font, ch)
            glyph_rows.append(
                "  {"
                f"{offset}U, "
                f"{meta['width']}U, "
                f"{meta['height']}U, "
                f"{meta['left']}, "
                f"{meta['top']}, "
                f"{meta['advance']}U"
                "}"
            )
            bitmap.extend(packed)
            offset += len(packed)

        glyphs_name = f"{spec.var_name}Glyphs"
        bitmap_name = f"{spec.var_name}Bitmap"
        out.append(f"inline constexpr Glyph {glyphs_name}[] = {{")
        out.append(",\n".join(glyph_rows))
        out.append("};")
        out.append("")
        out.append(f"inline constexpr std::uint8_t {bitmap_name}[] = {{")
        if bitmap:
            out.append(_format_bytes(bitmap))
        out.append("};")
        out.append("")
        out.append(
            f"inline constexpr BitmapFont {spec.var_name} = "
            "{"
            f"\"{spec.font_key}\", "
            f"{spec.size}U, "
            f"{ascent}U, "
            f"{descent}U, "
            f"{line_height}U, "
            f"{glyphs_name}, "
            f"{bitmap_name}, "
            f"sizeof({bitmap_name})"
            "};"
        )
        out.append("")

    out.append("}  // namespace fridge_ink::platform::panel_font_assets")
    out.append("")
    return "\n".join(out)


def main() -> None:
    text = generate()
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
