from __future__ import annotations

from pathlib import Path
from PIL import Image

REPO = Path(__file__).resolve().parents[1]
SRC_DIR = REPO / 'assets' / 'weather_icon_packs' / 'kickstand' / 'png'
OUT = REPO / 'firmware' / 'main' / 'ui' / 'weather_icon_assets_generated.hpp'
SIZE = 64
ALPHA_THRESHOLD = 160
ICONS = [
    ('Cloud', 'cloud'),
    ('Sun', 'sun'),
    ('PartlySunny', 'partly_sunny'),
    ('Rain', 'rain'),
    ('Snow', 'snow'),
    ('Storm', 'storm'),
    ('Haze', 'haze'),
    ('Hail', 'hail'),
    ('Moon', 'moon'),
    ('PartlyMoon', 'partly_moon'),
    ('Sunrise', 'sunrise'),
    ('Tornado', 'tornado'),
]

HEADER = f'''#pragma once

// Auto-generated by tools/generate_firmware_weather_icon_assets.py
// Source: assets/weather_icon_packs/kickstand/png/*-thin.png

namespace fridge_ink::ui::weather_icon_assets {{

constexpr int kKickstandThinGridSize = {SIZE};

'''
FOOTER = '\n}  // namespace fridge_ink::ui::weather_icon_assets\n'


def render_rows(path: Path) -> list[str]:
    im = Image.open(path).convert('RGBA')
    alpha = im.getchannel('A')
    bbox = alpha.getbbox()
    if bbox:
        im = im.crop(bbox)
    im = im.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    alpha = im.getchannel('A').point(lambda p: 255 if p >= ALPHA_THRESHOLD else 0)
    rows: list[str] = []
    for y in range(SIZE):
        row = ''.join('#' if alpha.getpixel((x, y)) else '.' for x in range(SIZE))
        rows.append(row)
    return rows


def write_icon(name: str, rows: list[str]) -> str:
    lines = [f'constexpr const char* kKickstand{name}Thin32[] = {{']
    for row in rows:
        lines.append(f'    "{row}",')
    lines.append('};\n')
    return '\n'.join(lines)


def main() -> None:
    chunks = [HEADER]
    for stem, var in ICONS:
        path = SRC_DIR / f'{stem}-thin.png'
        chunks.append(write_icon(stem, render_rows(path)))
    OUT.write_text(''.join(chunks) + FOOTER)
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
